# Automatidata project

**Welcome to the Automatidata Project!**

You have just started as a data professional in a fictional data consulting firm, Automatidata. Their client, the New York City Taxi and Limousine Commission (New York City TLC), has hired the Automatidata team for its reputation in helping their clients develop data-based solutions.

The team is still in the early stages of the project. Previously, you were asked to complete a project proposal by your supervisor, DeShawn Washington. You have received notice that your project proposal has been approved and that New York City TLC has given the Automatidata team access to their data. To get clear insights, New York TLC's data must be analyzed, key variables identified, and the dataset ensured it is ready for analysis.

#### Provided taxi cab dataset and information.
Create a pandas dataframe for data learning, and future exploratory data analysis (EDA) and statistical activities.

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv(r'C:\Users\Roshan Kumar\Desktop\GoogleAdvancedDA\Python\1\2017_Yellow_Taxi_Trip_Data.csv')
df
#In Python, the backslash \ is normally treated as an escape character. would confuse Python because \n means newline and \t means tab.
# By adding r before the string, you tell Python: “Treat everything inside as raw text, don’t interpret backslashes as escapes.”  
# path = "C:\new\test.txt"
# print(path)
# Output: C:
# ew    est.txt   (wrong, because \n = newline, \t = tab)

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.00,0.3,16.56
1,35634249,1,04/11/2017 2:53:28 PM,04/11/2017 3:19:58 PM,1,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.00,0.3,20.80
2,106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.00,0.3,8.75
3,38942136,2,05/07/2017 1:17:59 PM,05/07/2017 1:48:14 PM,1,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.00,0.3,27.69
4,30841670,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,1,4.37,1,N,4,112,2,16.5,0.5,0.5,0.00,0.00,0.3,17.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22694,14873857,2,02/24/2017 5:37:23 PM,02/24/2017 5:40:39 PM,3,0.61,1,N,48,186,2,4.0,1.0,0.5,0.00,0.00,0.3,5.80
22695,66632549,2,08/06/2017 4:43:59 PM,08/06/2017 5:24:47 PM,1,16.71,2,N,132,164,1,52.0,0.0,0.5,14.64,5.76,0.3,73.20
22696,74239933,2,09/04/2017 2:54:14 PM,09/04/2017 2:58:22 PM,1,0.42,1,N,107,234,2,4.5,0.0,0.5,0.00,0.00,0.3,5.30
22697,60217333,2,07/15/2017 12:56:30 PM,07/15/2017 1:08:26 PM,1,2.36,1,N,68,144,1,10.5,0.0,0.5,1.70,0.00,0.3,13.00
22698,17208911,1,03/02/2017 1:02:49 PM,03/02/2017 1:16:09 PM,1,2.10,1,N,239,236,1,11.0,0.0,0.5,2.35,0.00,0.3,14.15

#### **Understand the data - Inspect the data**

In [2]:
#View and inspect summary information about the dataframe

# df.head()
# df.tail()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22699 entries, 0 to 22698
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             22699 non-null  int64
 1   VendorID               22699 non-null  int64
 2   tpep_pickup_datetime   22699 non-null  object
 3   tpep_dropoff_datetime  22699 non-null  object
 4   passenger_count        22699 non-null  int64
 5   trip_distance          22699 non-null  float64
 6   RatecodeID             22699 non-null  int64
 7   store_and_fwd_flag     22699 non-null  object
 8   PULocationID           22699 non-null  int64
 9   DOLocationID           22699 non-null  int64
 10  payment_type           22699 non-null  int64
 11  fare_amount            22699 non-null  float64
 12  extra                  22699 non-null  float64
 13  mta_tax                22699 non-null  float64
 14  tip_amount             22699 non-null  float64
 15  tolls_amount           22699 non-null  float64
 16  improvement_surcharge  22699 non-null  float64
 17  total_amount           22699 non-null  float64
dtypes: float64(8), int64(7), object(3)
memory usage: 3.1+ MB

In [3]:
df.describe()

,Unnamed: 0,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
count,2.269900e+04,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000
mean,5.675849e+07,1.556236,1.642319,2.913313,1.043394,162.412353,161.527997,1.336887,13.026629,0.333275,0.497445,1.835781,0.312542,0.299551,16.310502
std,3.274493e+07,0.496838,1.285231,3.653171,0.708391,66.633373,70.139691,0.496211,13.243791,0.463097,0.039465,2.800626,1.399212,0.015673,16.097295
min,1.212700e+04,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,-120.000000,-1.000000,-0.500000,0.000000,0.000000,-0.300000,-120.300000
25%,2.852056e+07,1.000000,1.000000,0.990000,1.000000,114.000000,112.000000,1.000000,6.500000,0.000000,0.500000,0.000000,0.000000,0.300000,8.750000
50%,5.673150e+07,2.000000,1.000000,1.610000,1.000000,162.000000,162.000000,1.000000,9.500000,0.000000,0.500000,1.350000,0.000000,0.300000,11.800000
75%,8.537452e+07,2.000000,2.000000,3.060000,1.000000,233.000000,233.000000,2.000000,14.500000,0.500000,0.500000,2.450000,0.000000,0.300000,17.800000
max,1.134863e+08,2.000000,6.000000,33.960000,99.000000,265.000000,265.000000,4.000000,999.990000,4.500000,0.500000,200.000000,19.100000,0.300000,1200.290000

In [4]:
# df.size        #408582
# df.shape     #(22699, 18)

##### **Sort your first variable (trip_distance) from maximum to minimum value**

In [13]:
# df.sort_values(by=['trip_distance'],ascending=False)

trip_dist_sort = df.sort_values(by=['trip_distance'],ascending=False)
trip_dist_sort.head(3)

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
9280,51810714,2,06/18/2017 11:33:25 PM,06/19/2017 12:12:38 AM,2,33.96,5,N,132,265,2,150.00,0.0,0.0,0.00,0.00,0.3,150.30
13861,40523668,2,05/19/2017 8:20:21 AM,05/19/2017 9:20:30 AM,1,33.92,5,N,229,265,1,200.01,0.0,0.5,51.64,5.76,0.3,258.21
6064,49894023,2,06/13/2017 12:30:22 PM,06/13/2017 1:37:51 PM,1,32.72,3,N,138,1,1,107.00,0.0,0.0,55.50,16.26,0.3,179.06

##### **Sort by your second variable (`total_amount`)and print the bottom 20 values**

In [16]:
total_amt_sort = df.sort_values(by=['total_amount'], ascending=False)['total_amount']
total_amt_sort.tail(3)

17602     -5.8
20698     -5.8
12944   -120.3
Name: total_amount, dtype: float64

##### **How many of each payment type are represented in the data?**

In [25]:
# df['payment_type'].unique()    #array([1, 2, 3, 4], dtype=int64)

df['payment_type'].value_counts()

1    15265
2     7267
3      121
4       46
Name: payment_type, dtype: int64

##### **According to the data dictionary, the payment method was encoded as follows:**
1 = Credit card <br/>
2 = Cash <br/>
3 = No charge <br/>
4 = Dispute <br/>
5 = Unknown <br/>
6 = Voided trip**

##### **What is the average tip for trips paid for with credit card?**

In [29]:
# df['tip_amount'].mean() #1.8357813119520685
df[df['payment_type'] == 1]['tip_amount'].mean()

2.7298001965280054

##### **What is the average tip for trips paid for with cash?**

In [34]:
avg_cash_tip = df[df['payment_type'] == 2 ]['tip_amount'].mean()
print('Avg tip for trips paid with cash: ', avg_cash_tip)

Avg tip for trips paid with cash:  0.0

##### **How many times is each vendor ID represented in the data?**

In [41]:
df['VendorID'].value_counts()

2    12626
1    10073
Name: VendorID, dtype: int64

In [43]:
df.groupby(['VendorID']).size()

VendorID
1    10073
2    12626
dtype: int64

In [44]:
df['VendorID'].unique()

array([2, 1], dtype=int64)

##### **What is the mean total amount for each vendor?**

In [66]:
df.groupby(['VendorID'])['total_amount'].mean()

VendorID
1    16.298119
2    16.320382
Name: total_amount, dtype: float64

In [67]:
# df.groupby(['VendorID']).mean(numeric_only=True)[['total_amount']]
df.groupby(['VendorID']).mean()[['total_amount']]

          total_amount
VendorID
1            16.298119
2            16.320382

##### **Filter the data for credit card payments only**

In [75]:
credit_card = df[df['payment_type'] == 1]
credit_card.head(3)

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
1,35634249,1,04/11/2017 2:53:28 PM,04/11/2017 3:19:58 PM,1,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
2,106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75

##### **Filter the credit-card-only data for passenger count only**

In [79]:
# df['passenger_count'].unique()        #array([6, 1, 2, 4, 5, 3, 0], dtype=int64)
credit_card['passenger_count'].value_counts()

1    10977
2     2168
5      775
3      600
6      451
4      267
0       27
Name: passenger_count, dtype: int64

##### **Calculate the average tip amount for each passenger count (credit card payments only)**

In [76]:
df[df['payment_type'] == 1].groupby(['passenger_count'])['tip_amount'].mean()

passenger_count
0    2.610370
1    2.714681
2    2.829949
3    2.726800
4    2.607753
5    2.762645
6    2.643326
Name: tip_amount, dtype: float64

In [77]:
df[df['payment_type'] == 1].groupby(['passenger_count']).mean()[['tip_amount']]

                 tip_amount
passenger_count
0                  2.610370
1                  2.714681
2                  2.829949
3                  2.726800
4                  2.607753
5                  2.762645
6                  2.643326